// <auto-generated />
using System;
using MeterApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MeterApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeterApi.Models.Reading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apartment")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "apartment");

                    b.Property<decimal?>("GVS_Current")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "gvsCurrent");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "house");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "locality");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "note");

                    b.Property<string>("ReadingDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "readingDate");

                    b.Property<string>("Street")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "street");

                    b.Property<decimal>("XVS_Current")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "xvsCurrent");

                    b.HasKey("Id");

                    b.ToTable("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
